msrv = "1.56"

disallowed-methods = [
]

disallowed-types = [
    # Probably not suitable for any use case
    "std::collections::LinkedList",

    # Use the faster, simpler, and non-poisonable primitives in `parking_lot` instead
    "std::sync::Mutex",
    "std::sync::RwLock",
    "std::sync::CondVar",
]
