name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  continuous-integration:
    name: Building project and running tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Cache Rust toolchain and build artifacts
        uses: Swatinem/rust-cache@v1

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile

      - name: Build tests with default features disabled
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --locked --no-default-features --no-run

      - name: Build tests with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --locked --all-features --no-run

      - name: Run tests with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --locked --all-features -- --nocapture --quiet

      - name: Build workspace documentation with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --locked --all-features

      - name: Build release with default features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --profile release
